### ISSUE TITLE
Remove dependency on Modernizr

### ISSUE THREAD

**Issue by victoriafrench** [cinecove/defunctr#2]
Remove the dependency on Modernizr so that implementers can use the code in instances where IE detection is the only goal.

**Comment by mushtat** [comment]
I vote for this change too

**Comment by victoriafrench** [comment]
Are you guys using the css class features, javascript properties, or both? If nobody is using the properties attached to Modernizer (ie window.Modernizr.ie-6) then I don't have to worry about replicating the functionality.

**Comment by mushtat** [comment]
I've used both of this features (css and js)
